---
version: '3.8'
services:
  mysqldb:
    image: mysql:8.0.30
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: asu
      MYSQL_USER: app
      MYSQL_PASSWORD: 12345
    ports:
      - 3308:3306
        
  qdrant:
    image: qdrant/qdrant:v1.14.0
    container_name: qdrant
    ports:
      - "6335:6333"   # REST API
      - "6336:6334"   # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: