name: Publish Images service
#run-name: Publish Images service ${{ inputs.stand }}

on:
  workflow_dispatch:
#    inputs:

env:
  BUILD_DIR: buildfolder
  PUBLISH_DIR: publishfolder
  ARTIFACT_NAME: assembly
  DOTNET_VERSION: "9.0.x"

jobs:

  Build:
    runs-on: [self-hosted, imgrunner]
    steps:
      - name: checkout ðŸ›Žï¸
        uses: actions/checkout@v4
#      - name: setup dotnet
#        uses: actions/setup-dotnet@v2
#        with:
#          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: restore
        run: dotnet restore
      - name: build ðŸ—ï¸
        run: dotnet build --no-restore -c Release -o ${{ env.BUILD_DIR }}
#      - name: test ðŸ¦‘
#        run: dotnet test --no-restore --no-build -o ${{ env.BUILD_DIR }} Jeeroway.sln
      - name: publish
        run: dotnet publish src/JeerowayWiki.Images/JeerowayWiki.Images.csproj -c Release -o ${{ env.PUBLISH_DIR }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y_%m_%d__%H_%M_%S')"
        
      - name: Build docker image
        run: docker build --tag jeeroway-imgs:${{ steps.date.outputs.date }} ${{ env.PUBLISH_DIR }}/.

      - name: remove old container
        run: >
          if [ $( docker ps -a | grep "jeeroway-imgs" | wc -l ) -gt 0 ]; then 
            docker rm $(docker stop $(docker ps -a | grep "jeeroway-imgs" | cut -d " " -f 1)) 
          else
            echo 'container does not exists'
          fi

      - name: run new container
        run: |
          docker run \
            --restart unless-stopped \
            -p 80:8080 \
            -d \
            --name jimgs \
            --env ASPNETCORE_ENVIRONMENT=Release \
            --env ConnectionStrings__ImgConnection="${{ secrets.MYSQLIMGDBCONNECTION }}" \
            jeeroway-imgs:${{ steps.date.outputs.date }}


